### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by katyhuff** [jbae11/depletion_rom#28]
I suggested that some motivation is appropriate for the abstract. You added "... to implement a quick, medium-fidelity method to estimate depleted Pressurized Water Reactor (PWR) fuel assembly composition in a fuel cycle simulator". Actually, this is quite redundant with a sentence later in the abstract... "We also implemented... "

By "motivation," I mean we need a statement of need. "Why" was the work done? (e.g. Why do you need medium fidelity prediction of spent PWR fuel compositions in fuel cycle simulators... and why do people need fuel cycle simulators at all?)

**Comment by jbae11** [comment]
Thank you for the comment, I do see the point, but 
I think it'd be a bit lengthy to go all the way into why people need fuel cycle simulators at all.
Would saying that there was a gap be sufficient? I am not quite sure what the best way to phrase the motivation. Can you help me out? thanks

**Comment by jbae11** [comment]
@katyhuff  I modified the sentence to say:
```We trained a neural network model to predict Pressurized Water Reactor
(PWR) Used Nuclear Fuel (UNF) composition given initial enrichment and bur-
nup, to implement a quick, flexible, medium-fidelity method to estimate depleted
PWR fuel assembly composition to model scenarios where the PWR fuel burnup
and enrichment varies over time.```
I think the motivation for fuel cycle simulators are explained in the background and motivation section, so I skipped in. Thanks!

**Comment by jbae11** [comment]
@katyhuff ping

**Comment by jbae11** [comment]
@katyhuff Can you take a look at this for me? Let me know if there's something lacking.

**Comment by katyhuff** [comment]
Please see #29, which has a marked up pdf of the document, including comments in the motivation. I'll close this issue for now, in preference for the more comprehensive comments  in #29.
