### ISSUE TITLE
Address Huff Round 2 Comments 

### ISSUE THREAD

**Issue by katyhuff** [jbae11/depletion_rom#29]
@jbae11 My comments on round 2 of this document are attached. This issue can be closed with a PR that addresses the comments in the pdf. Mostly, my comments can be summarized thus:

- Looking much better. The results are cool.
- Comments attached. Grammatical issues throughout.
- Clarity is somewhat improved since the last version, but some clarity issues remain.
- Plots and tables have some issues.
- Please tightly review the conclusion.

[bae-round-2.pdf](https://github.com/jbae11/depletion_rom/files/3312252/bae-round-2.pdf)

**Comment by jbae11** [comment]
@katyhuff  We reflected your comments, I apologize for taking so long to finish this. Also, I think the paper would greatly benefit from your insight about other domains that are benefiting from digital repositories (right before future work). Please let me know if you have any additional comments. Thanks!

**Comment by katyhuff** [comment]
@jbae11 ... please read over it again, and carefully. I have noticed some grammatical errors in the abstract and the first sentence is not a sentence (that is, the first real sentence in the article... ). I assume more grammatical issues follow and I do not have the time to note them all again at this moment. Consider piping the document through a grammar checker... 

```
The Nuclear Fuel Cycle (NFC), a complex system of facilities and material mass flows that are combined to provide nuclear energy for use in society, usually in the form of electricity [1].
```

**Comment by jbae11** [comment]
@katyhuff I piped the document through a grammar checker, and gave the entire thing another read, in case it missed anything. Hopefully I covered all the errors. Let me know what you think! Thanks

**Comment by katyhuff** [comment]
Remaining issues:

- [ ] There is still no discussion about CLASS (NOTE: CLASS is basically the only simulator that has previously used trained neural networks as reactor models. Please cite and discuss, as this is the most important "competitor" to the work in the paper.... and they published on it 4 years ago in Annals... https://www.sciencedirect.com/science/article/pii/S0306454915001693)
- [ ] Use citations rather than footnotes (even if the citation is personal communication -- all bibliography styles have a way to cite personal communication). In the case of the github link, use a DOI. 
- [ ] All tables and figures should be mentioned and discussed in the text. A glance indicates that a few of them aren't. (Table 2, Figure 2, Figure 13, and maybe more)
- [ ] Capitalization of Table and Figure is inconsistent. In some places, Table is capitalized even in the middle of the sentence. Elsewhere, it's not. For simplicity, I recommend you capitalize "Figure" and "Table" everywhere.
- [ ] Rather than "SCALE ORIGEN" I usually see the following notation:  "SCALE/ORIGEN"


Other than that, I think it's probably ready to submit. I am guessing the reviewers may have some comments about the lack of depth in the literature review, and perhaps they'll have questions about the clarity of the figures. There's still lots of unnecessary passive voice, but, I suppose I've noted this previously, so maybe it remains because you've decided to prefer passive voice.

**Comment by jbae11** [comment]
@katyhuff Thank you for the review! I was able to resolve most of the bullet points but I am having a hard time resolving the first one. I tried to explain it in 71f76fe2ec3d2427cca84abfb1c2a762dfd4c571 but I believe that it's not enough. Do you have any ideas as to improve this mention of previous work? Thanks!

(I plan to run this section by Baptist so I don't misrepresent them.)

**Comment by katyhuff** [comment]
I probably can't get to this in the next few days. 
In short, you hit all of the right points, but it would be best to write more conversationally. There are too many sentences and I would avoid bullet points in this discussion. Try to be concise, if possible. Also, the narrative in the paragraph should communicate that the present work builds upon the previous work, extending it and drawing new conclusions. The thing to avoid is the notion that the present work is similar and redundant to other work (so perhaps avoid the word "similar"). The style that most authors use when discussing previous work typically has a pattern like:

 "In 2015, Smith et. al were the first to weave baskets underwater. Their freshwater approach to underwater basketweaving demonstrated that acceptable weaving precision could be coupled with enhanced challenges for the weaver. In the present work, our saltwater approach extends the conclusions of Smith et. al, by further enhancing challenges for the weaver via ocean currents and the manner in which saltwater stings the eyes."

Always: don't use "where" unless you're referring to a location.

**Comment by jbae11** [comment]
thank you for your advice. I rewrote the thing to fit the pattern you suggested. I think I am trying to balance between being respectful to Leniau et al. and demonstrating this paper is an extension.  Let me know what you think. Thanks!

**Comment by katyhuff** [comment]
looks good. Go ahead and submit!
