### ISSUE TITLE
Name the type of ANN

### ISSUE THREAD

**Issue by katyhuff** [jbae11/depletion_rom#30]
The paper is very vague with regard to the type of ANN used. The paper generally refers to this as a "neural network model". This is not very satisfying as a reader. Since you're using Keras' Sequential() model with some hidden layers, and because you use K-Folds... I'd call this a Dense Neural Network (with K-folds cross-validation).  If I'm interpreting the situation correctly, maybe refer to it this way throughout the paper?

**Comment by jbae11** [comment]
@katyhuff You definitely saw me through! That is a very good idea, embarrassingly enough, I didn't know the differences between neural network types when writing this paper. I'll make the edits! Thanks

**Comment by katyhuff** [comment]
Great! Thanks!
