### ISSUE TITLE
Andrei's comment after review

### ISSUE THREAD

**Issue by andrewryh** [jbae11/depletion_rom#35]
@jbae11 
Few very minor comment (probably, it's too late to make these changes, but consider it):

- [ ] Please, consider add one sentence describing what kind of data is in UDB. Probably, it is obvious for experts, but I think it is a good place to mention range of burnup and enrichment to address Reviewer #1 concern. Anyway, try to inject enrichment and burnup range of your training set into the Abstract.
- [x] p.3, line 29-30: You already introduced ORIGEN acronym in the Abstract. Do not do this second time.
- [x] p.3, Table 1: first row, give it little bit more space.
- [x] p.4, line 70: what is 'CLASS'? Give explanation or remove 'in the FCS CLASS' completely.
- [x] p.7, lines 114-117: Either have dot in the end of each \item or remove it.
- [ ] Table 4: Consider remove all vertical lines needed in this table.

**Comment by jbae11** [comment]
thanks @andrewryh. I reflected the comments with the checkmarks. For the first point, I think the plot should explain the range of data in the UDB. For the last point, I think the vertical lines help separate the actual data (`answer`), and predictions

**Comment by andrewryh** [comment]
> thanks @andrewryh. I reflected the comments with the checkmarks. For the first point, I think the plot should explain the range of data in the UDB. 
THat is right, but explicitly mentioned in the text (Abstract) would address the reviewer #1 comment.
But the main issues is this: you CANNOR extrapolate results. So, you can make your prediction ONLY withing training set range (Bu 10-70; enrichment 2-5%).  Panelist on yesterday's AI panel mentioned this multiple times. I would state in discussion or conclusions this, and you will automatically drop out questions about export control (because you limit enrichment in the pickle file).

>For the last point, I think the vertical lines help separate the actual data (`answer`), and predictions
Good idea; got it.
