### ISSUE TITLE
write about how UNF-ST&DARDS ran their ORIGEN simulations

### ISSUE THREAD

**Issue by jbae11** [jbae11/depletion_rom#4]
The paper needs a description of how the UDB depletion calculations were generated, complete with assumptions, results, software used, and what data was used to generate the depletion calculations (`total_mass_g`)

**Comment by gwenchee** [comment]
Should we mention explicitly that the database is received through a personal contact (kinda awkward to say that in the paper?). Or just that the database is used.

**Comment by gwenchee** [comment]
@jbae11

**Comment by jbae11** [comment]
Yeah I think it's best to say personal contact. However, I'm a little hesitant because we are just students..
I think it'd be best to talk to prof.Huff about how to navigate this, but I'm not sure if she has the time to look at this...

**Comment by gwenchee** [comment]
okay i'll ask her about it in my meeting on wednesday

**Comment by jbae11** [comment]
merged #14
